apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-blue
  labels:
    app: frontend
    release: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      release: v1
  template:
    metadata:
      labels:
        app: frontend
        release: v1
    spec:
      containers:
      - name: frontend
        image: lxqhim/smart-bank-frontend:blue
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 300Mi
